name: ml-regimes
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas>=2.2
  - numpy>=1.26
  - pyarrow>=15.0
  - matplotlib>=3.8
  - scikit-learn>=1.4
  - xgboost>=2.0
  - pip>=24.0
  - yaml
  - pip:
      - yfinance>=0.2.40
      - PyYAML>=6.0
      # Optional (comment out if not using LSTM)
      - tensorflow>=2.15; platform_system != "Darwin" or platform_machine != "arm64"
